// cmd/soak/main.go — entrypoint for the standalone `soak` binary: cobra root with `universe-file`/`duration`/`qps`/`failure-rate`/memory-check flags, loads config, builds an `Orchestrator`, and runs it to completion. Capacity: 1 cobra root + 14 flags + 1 `runSoak` RunE + `main`.
package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/bizshuk/yfin/config"
	"github.com/spf13/cobra"
)

// Global config structure for CLI flags
type GlobalConfig struct {
	ConfigFile  string
	LogLevel    string
	RunID       string
	Concurrency int
	QPS         float64
	RetryMax    int
	Timeout     time.Duration
}

var (
	globalConfig GlobalConfig
	soakConfig   SoakConfig
)

var rootCmd = &cobra.Command{
	Use:   "soak",
	Short: "Run comprehensive soak tests for stability and robustness",
	Long: `Run production-like soak tests across a diverse ticker universe to validate:
- Stability and throughput under sustained load
- Backoff and retry behavior under rate limiting
- Robots.txt compliance and session rotation
- API vs scrape correctness validation
- Memory and goroutine leak detection
- End-to-end pipeline robustness`,
	RunE: runSoak,
}

func init() {
	// Persistent flags (equivalent to yfin root flags used by soak)
	rootCmd.PersistentFlags().StringVar(&globalConfig.ConfigFile, "config", "", "ampy-config file (optional)")
	rootCmd.PersistentFlags().StringVar(&globalConfig.LogLevel, "log-level", "info", "Log level (info|debug|warn|error)")
	rootCmd.PersistentFlags().StringVar(&globalConfig.RunID, "run-id", "", "Run ID for tracking (if empty, autogenerated)")
	rootCmd.PersistentFlags().IntVar(&globalConfig.Concurrency, "concurrency", 0, "Worker pool size (default from config)")
	rootCmd.PersistentFlags().Float64Var(&globalConfig.QPS, "qps", 0, "Per-host QPS (default from config)")
	rootCmd.PersistentFlags().IntVar(&globalConfig.RetryMax, "retry-max", 0, "HTTP retry attempts")
	rootCmd.PersistentFlags().DurationVar(&globalConfig.Timeout, "timeout", 0, "HTTP timeout (e.g., 6s)")

	// Soak command flags
	rootCmd.Flags().StringVar(&soakConfig.UniverseFile, "universe-file", "", "File containing list of tickers to test (required)")
	rootCmd.Flags().StringVar(&soakConfig.Endpoints, "endpoints", "key-statistics,financials,analysis,profile,news", "Comma-separated list of endpoints to test")
	rootCmd.Flags().StringVar(&soakConfig.Fallback, "fallback", "auto", "Fallback strategy: auto, api-only, scrape-only")
	rootCmd.Flags().DurationVar(&soakConfig.Duration, "duration", 2*time.Hour, "Duration to run soak test")
	rootCmd.Flags().IntVar(&soakConfig.Concurrency, "concurrency", 12, "Number of concurrent workers")
	rootCmd.Flags().Float64Var(&soakConfig.QPS, "qps", 5.0, "Target queries per second")
	rootCmd.Flags().DurationVar(&soakConfig.ProbeInterval, "probe-interval", 1*time.Hour, "Interval for correctness probes")
	rootCmd.Flags().Float64Var(&soakConfig.FailureRate, "failure-rate", 0.1, "Simulated failure rate for testing (0.0-1.0)")
	rootCmd.Flags().BoolVar(&soakConfig.MemoryCheck, "memory-check", true, "Enable memory and goroutine leak detection")

	_ = rootCmd.MarkFlagRequired("universe-file")
}

func runSoak(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	// Load configuration
	loader := config.NewLoader(globalConfig.ConfigFile)
	cfg, err := loader.Load()
	if err != nil {
		return fmt.Errorf("failed to load config: %w", err)
	}

	// NOTE: CLI overrides for --qps / --retry-max / --timeout are bound as flags
	// but not yet wired into *config.Config after the nested-struct refactor.
	// Apply them via cfg.GetHTTPConfig() + cfg.Yahoo.TimeoutMs / cfg.RateLimit.PerHostQPS /
	// cfg.Retry.Attempts when orchestrator override hooks are available.
	_ = cfg // keep cfg referenced for now

	// Initialize soak test orchestrator
	orchestrator, err := NewOrchestrator(cfg, &soakConfig)
	if err != nil {
		return fmt.Errorf("failed to create soak orchestrator: %w", err)
	}
	defer orchestrator.Close()

	// Run soak test
	if err := orchestrator.Run(ctx); err != nil {
		return fmt.Errorf("soak test failed: %w", err)
	}

	return nil
}

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
