// global.go — shared persistent CLI flags (`--config` / `--log-level` /
// `--run-id` / `--concurrency` / `--qps` / `--retry-max` / `--sessions` /
// `--timeout` / observability toggles) and the `GlobalConfig` struct/state.
// These flags propagate to every cobra subcommand because they are bound on
// `rootCmd.PersistentFlags()`. The exported `Global` var is read by every
// sub-package under `cmd/` (market/fundamentals/scrape/admin/dispatch/twse).
// Capacity: 1 `GlobalConfig` + 1 exported `Global` var + 1 `init()` that
// binds all persistent flags.
package cmd

import (
	"time"

	"github.com/bizshuk/gosdk/log"
)

// _ keeps gosdk/log referenced at compile time — its package-level init()
// installs the slog.Default handler that the rest of the CLI uses.
var _ = log.GetLogLevel

// GlobalConfig holds the persistent flags shared by every yfin subcommand.
type GlobalConfig struct {
	ConfigFile  string
	LogLevel    string
	RunID       string
	Concurrency int
	QPS         float64
	RetryMax    int
	Sessions    int
	Timeout     time.Duration
}

// Global is the shared instance every sub-package reads. Exported so that
// sub-package code can do `cmd.Global.RunID` without an accessor layer.
var Global GlobalConfig

func init() {
	// Global flags
	RootCmd.PersistentFlags().StringVar(&Global.ConfigFile, "config", "", "ampy-config file (optional)")
	RootCmd.PersistentFlags().StringVar(&Global.LogLevel, "log-level", "info", "Log level (info|debug|warn|error)")
	RootCmd.PersistentFlags().StringVar(&Global.RunID, "run-id", "", "Run ID for tracking (if empty, autogenerated)")
	RootCmd.PersistentFlags().IntVar(&Global.Concurrency, "concurrency", 0, "Worker pool size (default from config)")
	RootCmd.PersistentFlags().Float64Var(&Global.QPS, "qps", 0, "Per-host QPS (default from config)")
	RootCmd.PersistentFlags().IntVar(&Global.RetryMax, "retry-max", 0, "HTTP retry attempts")
	RootCmd.PersistentFlags().IntVar(&Global.Sessions, "sessions", 0, "Session rotation pool size")
	RootCmd.PersistentFlags().DurationVar(&Global.Timeout, "timeout", 0, "HTTP timeout (e.g., 6s)")

	// Observability flags
	RootCmd.PersistentFlags().Bool("observability-disable-tracing", false, "Disable OpenTelemetry tracing")
	RootCmd.PersistentFlags().Bool("observability-disable-metrics", false, "Disable Prometheus metrics")
}
