// global.go — shared persistent CLI flags (`--config` / `--log-level` /
// `--run-id` / `--concurrency` / `--qps` / `--retry-max` / `--sessions` /
// `--timeout` / observability toggles) and the `GlobalConfig` struct/state.
// These flags propagate to every cobra subcommand because they are bound on
// `rootCmd.PersistentFlags()`. Capacity: 1 `GlobalConfig` + 1 package-level
// `globalConfig` var + 1 `init()` that binds all persistent flags.
package cmd

import (
	"time"

	"github.com/bizshuk/gosdk/log"
)

// _ keeps gosdk/log referenced at compile time — its package-level init()
// installs the slog.Default handler that the rest of the CLI uses.
var _ = log.GetLogLevel

// GlobalConfig holds the persistent flags shared by every yfin subcommand.
type GlobalConfig struct {
	ConfigFile  string
	LogLevel    string
	RunID       string
	Concurrency int
	QPS         float64
	RetryMax    int
	Sessions    int
	Timeout     time.Duration
}

var globalConfig GlobalConfig

func init() {
	// Global flags
	rootCmd.PersistentFlags().StringVar(&globalConfig.ConfigFile, "config", "", "ampy-config file (optional)")
	rootCmd.PersistentFlags().StringVar(&globalConfig.LogLevel, "log-level", "info", "Log level (info|debug|warn|error)")
	rootCmd.PersistentFlags().StringVar(&globalConfig.RunID, "run-id", "", "Run ID for tracking (if empty, autogenerated)")
	rootCmd.PersistentFlags().IntVar(&globalConfig.Concurrency, "concurrency", 0, "Worker pool size (default from config)")
	rootCmd.PersistentFlags().Float64Var(&globalConfig.QPS, "qps", 0, "Per-host QPS (default from config)")
	rootCmd.PersistentFlags().IntVar(&globalConfig.RetryMax, "retry-max", 0, "HTTP retry attempts")
	rootCmd.PersistentFlags().IntVar(&globalConfig.Sessions, "sessions", 0, "Session rotation pool size")
	rootCmd.PersistentFlags().DurationVar(&globalConfig.Timeout, "timeout", 0, "HTTP timeout (e.g., 6s)")

	// Observability flags
	rootCmd.PersistentFlags().Bool("observability-disable-tracing", false, "Disable OpenTelemetry tracing")
	rootCmd.PersistentFlags().Bool("observability-disable-metrics", false, "Disable Prometheus metrics")
}
